### ISSUE TITLE
remove missing county info

### ISSUE THREAD

**Issue by mapdonnelly** [CDPHrusers/heatProjection#5]
remove the records where patient county is 0, or patient zip code is missing (~345,000 records for the study period (~16,000 missing zips, ~330,000 out of state zips))
```
is.na(patzip) |  patco == 0
```

**Comment by mapdonnelly** [comment]
added subsetting to `filter_ed` function to remove county ==0

**Comment by vargovargo** [comment]
ultimately did this by keeping all records where `patco != 0`
